[package]
name = "uuidgen"
version = "0.1.0"
authors = ["Anton Moilanen <anton.a.moilanen@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"