FOOD_PREFERENCES = {
    'pea soup': 11,
    'meat balls': 8,
    'meatballs': 8,
    'meat': 6,
    'pork': 6,
    'beef': 6,
    'game': 6,
    'hamburger': 6,
    'chicken': 5,
    'broiler': 5,
    'fish': 4,
    'salmon': 4,
    'tuna': 4,
    'hernekeitto': 11,
    'lihapull': 8,
    'liha': 6,
    'porsaan': 6,
    'naudan': 6,
    'ristä': 6,
    'hampuri': 6,
    'kana': 5,
    'broileri': 5,
    'kala': 4,
    'lohi': 4,
    'tonnikala': 4
}