apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-generator-config
data:
  kafka-bootstrap-servers: "kafka-cluster:9092"
  kafka-topic: "invoice-events"
  gcp-project-id: "your-gcp-project-id"
  gcp-bucket-name: "invoice-pdfs"
---
apiVersion: v1
kind: Secret
metadata:
  name: invoice-generator-secrets
type: Opaque
data:
  database-url: "amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTU0MzIvaW52b2ljZV9nZW5lcmF0b3I="
  database-username: "cG9zdGdyZXM="
  database-password: "cGFzc3dvcmQ="
---
apiVersion: v1
kind: Secret
metadata:
  name: google-cloud-key
type: Opaque
data:
  key.json: "PLACE_YOUR_BASE64_ENCODED_SERVICE_ACCOUNT_KEY_HERE" 