apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetty-backend
  labels:
    app: budgetty-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgetty-backend
  template:
    metadata:
      labels:
        app: budgetty-backend
    spec:
      containers:
      - name: budgetty-backend
        #image: gcr.io/<YOUR_PROJECT_ID>/budgetty-backend:latest
        image: budgetty-backend:local
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          value: "7d"
        - name: FRONTEND_URL
          #value: "https://budgetty.example.com"
          value: "http://localhost:5173"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: API_URL
          #value: "https://api.budgetty.example.com"
          value: "http://localhost:3001"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20 