apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetty-backend
  labels:
    app: budgetty-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budgetty-backend
  template:
    metadata:
      labels:
        app: budgetty-backend
    spec:
      containers:
      - name: budgetty-backend
        image: gcr.io/budgetty/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "1d"
        - name: FRONTEND_URL
          value: "https://budgetty.example.com"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: google-client-secret
        - name: GOOGLE_CALLBACK_URL
          value: "https://api.budgetty.example.com/auth/google/callback"
        - name: ALLOWED_EMAILS
          valueFrom:
            secretKeyRef:
              name: budgetty-secrets
              key: allowed-emails
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20 