[package]
name = "invoice-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bigdecimal = "0.4.7"
font-kit = "0.14.2"
printpdf = "0.7.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
